// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto.proto

package name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto;

public final class ExampleProto {
  private ExampleProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_name_jchein_portfolio_random_art_CreatePaintArtworkTask_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_name_jchein_portfolio_random_art_CreatePaintArtworkTask_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_name_jchein_portfolio_random_art_CancelPaintArtworkTask_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_name_jchein_portfolio_random_art_CancelPaintArtworkTask_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_name_jchein_portfolio_random_art_SuspendPaintArtworkTask_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_name_jchein_portfolio_random_art_SuspendPaintArtworkTask_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_name_jchein_portfolio_random_art_ResumePaintArtworkTask_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_name_jchein_portfolio_random_art_ResumePaintArtworkTask_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_name_jchein_portfolio_random_art_RetryPaintArtworkTask_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_name_jchein_portfolio_random_art_RetryPaintArtworkTask_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_name_jchein_portfolio_random_art_AcknowledgePaintArtworkTask_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_name_jchein_portfolio_random_art_AcknowledgePaintArtworkTask_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_name_jchein_portfolio_random_art_CommandReceived_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_name_jchein_portfolio_random_art_CommandReceived_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_name_jchein_portfolio_random_art_PercentDoneUpdate_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_name_jchein_portfolio_random_art_PercentDoneUpdate_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_name_jchein_portfolio_random_art_InformationUpdate_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_name_jchein_portfolio_random_art_InformationUpdate_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_name_jchein_portfolio_random_art_RetryableErrorUpdate_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_name_jchein_portfolio_random_art_RetryableErrorUpdate_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_name_jchein_portfolio_random_art_UpdatePaintArtworkTask_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_name_jchein_portfolio_random_art_UpdatePaintArtworkTask_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013proto.proto\022 name.jchein.portfolio.ran" +
      "dom_art\"\213\001\n\026CreatePaintArtworkTask\022\n\n\002id" +
      "\030\001 \001(\t\022\022\n\nseedPrefix\030\007 \001(\t\022\022\n\nseedSuffix" +
      "\030\010 \001(\t\022\020\n\010newModel\030\t \001(\010\022\024\n\014renderPolicy" +
      "\030\n \001(\t\022\025\n\rstagingPolicy\030\013 \001(\t\"1\n\026CancelP" +
      "aintArtworkTask\022\n\n\002id\030\001 \001(\t\022\013\n\003seq\030\002 \001(\r" +
      "\"2\n\027SuspendPaintArtworkTask\022\n\n\002id\030\001 \001(\t\022" +
      "\013\n\003seq\030\002 \001(\r\"1\n\026ResumePaintArtworkTask\022\n" +
      "\n\002id\030\001 \001(\t\022\013\n\003seq\030\002 \001(\r\"0\n\025RetryPaintArt" +
      "workTask\022\n\n\002id\030\001 \001(\t\022\013\n\003seq\030\002 \001(\r\"6\n\033Ack" +
      "nowledgePaintArtworkTask\022\n\n\002id\030\001 \001(\t\022\013\n\003" +
      "seq\030\002 \001(\r\"J\n\017CommandReceived\022\n\n\002id\030\001 \001(\t" +
      "\022\013\n\003seq\030\002 \001(\r\022\014\n\004type\030\003 \001(\t\022\020\n\010accepted\030" +
      "\004 \001(\010\"9\n\021PercentDoneUpdate\022\017\n\007message\030\003 " +
      "\001(\t\022\023\n\013percentDone\030\004 \001(\r\"$\n\021InformationU" +
      "pdate\022\017\n\007message\030\003 \001(\t\"8\n\024RetryableError" +
      "Update\022\017\n\007message\030\003 \001(\t\022\017\n\007retryIn\030\004 \001(\r" +
      "\"\363\002\n\026UpdatePaintArtworkTask\022\n\n\002id\030\001 \001(\t\022" +
      "\013\n\003seq\030\002 \001(\r\022@\n\nupdateType\030\003 \001(\0162,.name." +
      "jchein.portfolio.random_art.UpdateType\022N" +
      "\n\017percentDoneBody\030\r \001(\01323.name.jchein.po" +
      "rtfolio.random_art.PercentDoneUpdateH\000\022N" +
      "\n\017informationBody\030\016 \001(\01323.name.jchein.po" +
      "rtfolio.random_art.InformationUpdateH\000\022P" +
      "\n\016retryErrorBody\030\017 \001(\01326.name.jchein.por" +
      "tfolio.random_art.RetryableErrorUpdateH\000" +
      "B\014\n\nupdateBody*\273\001\n\nUpdateType\022\022\n\016IN_PAIN" +
      "T_QUEUE\020\000\022\023\n\017IN_UPLOAD_QUEUE\020\001\022\022\n\016PAINT_" +
      "PROGRESS\020\002\022\r\n\tUPLOADING\020\003\022\n\n\006PAUSED\020\004\022\016\n" +
      "\nSOFT_ERROR\020\005\022\017\n\013FATAL_ERROR\020\006\022\014\n\010FINISH" +
      "ED\020\007\022\r\n\tCANCELLED\020\010\022\013\n\007DROPPED\020\t\022\n\n\006CLOS" +
      "ED\020\n2\274\004\n\014PaintGateway\022\214\001\n\027createPaintArt" +
      "workTasks\0228.name.jchein.portfolio.random" +
      "_art.CreatePaintArtworkTask\0321.name.jchei" +
      "n.portfolio.random_art.CommandReceived\"\000" +
      "(\0010\001\022\211\001\n\026createPaintArtworkTask\0228.name.j" +
      "chein.portfolio.random_art.CreatePaintAr" +
      "tworkTask\0321.name.jchein.portfolio.random" +
      "_art.CommandReceived\"\0000\001\022\211\001\n\026cancelPaint" +
      "ArtworkTask\0228.name.jchein.portfolio.rand" +
      "om_art.CancelPaintArtworkTask\0321.name.jch" +
      "ein.portfolio.random_art.CommandReceived" +
      "\"\0000\001\022\204\001\n\017reportTaskState\0228.name.jchein.p" +
      "ortfolio.random_art.UpdatePaintArtworkTa" +
      "sk\0321.name.jchein.portfolio.random_art.Co" +
      "mmandReceived\"\000(\0010\001BR\n@name.jchein.portf" +
      "olio.services.randomArt.paintGateway.grp" +
      "c.protoB\014ExampleProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_name_jchein_portfolio_random_art_CreatePaintArtworkTask_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_name_jchein_portfolio_random_art_CreatePaintArtworkTask_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_name_jchein_portfolio_random_art_CreatePaintArtworkTask_descriptor,
        new java.lang.String[] { "Id", "SeedPrefix", "SeedSuffix", "NewModel", "RenderPolicy", "StagingPolicy", });
    internal_static_name_jchein_portfolio_random_art_CancelPaintArtworkTask_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_name_jchein_portfolio_random_art_CancelPaintArtworkTask_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_name_jchein_portfolio_random_art_CancelPaintArtworkTask_descriptor,
        new java.lang.String[] { "Id", "Seq", });
    internal_static_name_jchein_portfolio_random_art_SuspendPaintArtworkTask_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_name_jchein_portfolio_random_art_SuspendPaintArtworkTask_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_name_jchein_portfolio_random_art_SuspendPaintArtworkTask_descriptor,
        new java.lang.String[] { "Id", "Seq", });
    internal_static_name_jchein_portfolio_random_art_ResumePaintArtworkTask_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_name_jchein_portfolio_random_art_ResumePaintArtworkTask_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_name_jchein_portfolio_random_art_ResumePaintArtworkTask_descriptor,
        new java.lang.String[] { "Id", "Seq", });
    internal_static_name_jchein_portfolio_random_art_RetryPaintArtworkTask_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_name_jchein_portfolio_random_art_RetryPaintArtworkTask_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_name_jchein_portfolio_random_art_RetryPaintArtworkTask_descriptor,
        new java.lang.String[] { "Id", "Seq", });
    internal_static_name_jchein_portfolio_random_art_AcknowledgePaintArtworkTask_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_name_jchein_portfolio_random_art_AcknowledgePaintArtworkTask_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_name_jchein_portfolio_random_art_AcknowledgePaintArtworkTask_descriptor,
        new java.lang.String[] { "Id", "Seq", });
    internal_static_name_jchein_portfolio_random_art_CommandReceived_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_name_jchein_portfolio_random_art_CommandReceived_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_name_jchein_portfolio_random_art_CommandReceived_descriptor,
        new java.lang.String[] { "Id", "Seq", "Type", "Accepted", });
    internal_static_name_jchein_portfolio_random_art_PercentDoneUpdate_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_name_jchein_portfolio_random_art_PercentDoneUpdate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_name_jchein_portfolio_random_art_PercentDoneUpdate_descriptor,
        new java.lang.String[] { "Message", "PercentDone", });
    internal_static_name_jchein_portfolio_random_art_InformationUpdate_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_name_jchein_portfolio_random_art_InformationUpdate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_name_jchein_portfolio_random_art_InformationUpdate_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_name_jchein_portfolio_random_art_RetryableErrorUpdate_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_name_jchein_portfolio_random_art_RetryableErrorUpdate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_name_jchein_portfolio_random_art_RetryableErrorUpdate_descriptor,
        new java.lang.String[] { "Message", "RetryIn", });
    internal_static_name_jchein_portfolio_random_art_UpdatePaintArtworkTask_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_name_jchein_portfolio_random_art_UpdatePaintArtworkTask_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_name_jchein_portfolio_random_art_UpdatePaintArtworkTask_descriptor,
        new java.lang.String[] { "Id", "Seq", "UpdateType", "PercentDoneBody", "InformationBody", "RetryErrorBody", "UpdateBody", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
