// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto.proto

package name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto;

public interface InformationUpdateOrBuilder extends
    // @@protoc_insertion_point(interface_extends:name.jchein.portfolio.random_art.InformationUpdate)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 3;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 3;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
