// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto.proto

package name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto;

public interface RetryPaintArtworkTaskOrBuilder extends
    // @@protoc_insertion_point(interface_extends:name.jchein.portfolio.random_art.RetryPaintArtworkTask)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>uint32 seq = 2;</code>
   */
  int getSeq();
}
