// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto.proto

package name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto;

/**
 * Protobuf type {@code name.jchein.portfolio.random_art.UpdatePaintArtworkTask}
 */
public  final class UpdatePaintArtworkTask extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:name.jchein.portfolio.random_art.UpdatePaintArtworkTask)
    UpdatePaintArtworkTaskOrBuilder {
private static final long serialVersionUID = 0L;
  // Use UpdatePaintArtworkTask.newBuilder() to construct.
  private UpdatePaintArtworkTask(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private UpdatePaintArtworkTask() {
    id_ = "";
    seq_ = 0;
    updateType_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private UpdatePaintArtworkTask(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            id_ = s;
            break;
          }
          case 16: {

            seq_ = input.readUInt32();
            break;
          }
          case 24: {
            int rawValue = input.readEnum();

            updateType_ = rawValue;
            break;
          }
          case 106: {
            name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.PercentDoneUpdate.Builder subBuilder = null;
            if (updateBodyCase_ == 13) {
              subBuilder = ((name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.PercentDoneUpdate) updateBody_).toBuilder();
            }
            updateBody_ =
                input.readMessage(name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.PercentDoneUpdate.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.PercentDoneUpdate) updateBody_);
              updateBody_ = subBuilder.buildPartial();
            }
            updateBodyCase_ = 13;
            break;
          }
          case 114: {
            name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.InformationUpdate.Builder subBuilder = null;
            if (updateBodyCase_ == 14) {
              subBuilder = ((name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.InformationUpdate) updateBody_).toBuilder();
            }
            updateBody_ =
                input.readMessage(name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.InformationUpdate.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.InformationUpdate) updateBody_);
              updateBody_ = subBuilder.buildPartial();
            }
            updateBodyCase_ = 14;
            break;
          }
          case 122: {
            name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.RetryableErrorUpdate.Builder subBuilder = null;
            if (updateBodyCase_ == 15) {
              subBuilder = ((name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.RetryableErrorUpdate) updateBody_).toBuilder();
            }
            updateBody_ =
                input.readMessage(name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.RetryableErrorUpdate.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.RetryableErrorUpdate) updateBody_);
              updateBody_ = subBuilder.buildPartial();
            }
            updateBodyCase_ = 15;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.ExampleProto.internal_static_name_jchein_portfolio_random_art_UpdatePaintArtworkTask_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.ExampleProto.internal_static_name_jchein_portfolio_random_art_UpdatePaintArtworkTask_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.UpdatePaintArtworkTask.class, name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.UpdatePaintArtworkTask.Builder.class);
  }

  private int updateBodyCase_ = 0;
  private java.lang.Object updateBody_;
  public enum UpdateBodyCase
      implements com.google.protobuf.Internal.EnumLite {
    PERCENTDONEBODY(13),
    INFORMATIONBODY(14),
    RETRYERRORBODY(15),
    UPDATEBODY_NOT_SET(0);
    private final int value;
    private UpdateBodyCase(int value) {
      this.value = value;
    }
    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static UpdateBodyCase valueOf(int value) {
      return forNumber(value);
    }

    public static UpdateBodyCase forNumber(int value) {
      switch (value) {
        case 13: return PERCENTDONEBODY;
        case 14: return INFORMATIONBODY;
        case 15: return RETRYERRORBODY;
        case 0: return UPDATEBODY_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public UpdateBodyCase
  getUpdateBodyCase() {
    return UpdateBodyCase.forNumber(
        updateBodyCase_);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private volatile java.lang.Object id_;
  /**
   * <code>string id = 1;</code>
   */
  public java.lang.String getId() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      id_ = s;
      return s;
    }
  }
  /**
   * <code>string id = 1;</code>
   */
  public com.google.protobuf.ByteString
      getIdBytes() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      id_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SEQ_FIELD_NUMBER = 2;
  private int seq_;
  /**
   * <code>uint32 seq = 2;</code>
   */
  public int getSeq() {
    return seq_;
  }

  public static final int UPDATETYPE_FIELD_NUMBER = 3;
  private int updateType_;
  /**
   * <code>.name.jchein.portfolio.random_art.UpdateType updateType = 3;</code>
   */
  public int getUpdateTypeValue() {
    return updateType_;
  }
  /**
   * <code>.name.jchein.portfolio.random_art.UpdateType updateType = 3;</code>
   */
  public name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.UpdateType getUpdateType() {
    @SuppressWarnings("deprecation")
    name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.UpdateType result = name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.UpdateType.valueOf(updateType_);
    return result == null ? name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.UpdateType.UNRECOGNIZED : result;
  }

  public static final int PERCENTDONEBODY_FIELD_NUMBER = 13;
  /**
   * <code>.name.jchein.portfolio.random_art.PercentDoneUpdate percentDoneBody = 13;</code>
   */
  public boolean hasPercentDoneBody() {
    return updateBodyCase_ == 13;
  }
  /**
   * <code>.name.jchein.portfolio.random_art.PercentDoneUpdate percentDoneBody = 13;</code>
   */
  public name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.PercentDoneUpdate getPercentDoneBody() {
    if (updateBodyCase_ == 13) {
       return (name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.PercentDoneUpdate) updateBody_;
    }
    return name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.PercentDoneUpdate.getDefaultInstance();
  }
  /**
   * <code>.name.jchein.portfolio.random_art.PercentDoneUpdate percentDoneBody = 13;</code>
   */
  public name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.PercentDoneUpdateOrBuilder getPercentDoneBodyOrBuilder() {
    if (updateBodyCase_ == 13) {
       return (name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.PercentDoneUpdate) updateBody_;
    }
    return name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.PercentDoneUpdate.getDefaultInstance();
  }

  public static final int INFORMATIONBODY_FIELD_NUMBER = 14;
  /**
   * <code>.name.jchein.portfolio.random_art.InformationUpdate informationBody = 14;</code>
   */
  public boolean hasInformationBody() {
    return updateBodyCase_ == 14;
  }
  /**
   * <code>.name.jchein.portfolio.random_art.InformationUpdate informationBody = 14;</code>
   */
  public name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.InformationUpdate getInformationBody() {
    if (updateBodyCase_ == 14) {
       return (name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.InformationUpdate) updateBody_;
    }
    return name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.InformationUpdate.getDefaultInstance();
  }
  /**
   * <code>.name.jchein.portfolio.random_art.InformationUpdate informationBody = 14;</code>
   */
  public name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.InformationUpdateOrBuilder getInformationBodyOrBuilder() {
    if (updateBodyCase_ == 14) {
       return (name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.InformationUpdate) updateBody_;
    }
    return name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.InformationUpdate.getDefaultInstance();
  }

  public static final int RETRYERRORBODY_FIELD_NUMBER = 15;
  /**
   * <code>.name.jchein.portfolio.random_art.RetryableErrorUpdate retryErrorBody = 15;</code>
   */
  public boolean hasRetryErrorBody() {
    return updateBodyCase_ == 15;
  }
  /**
   * <code>.name.jchein.portfolio.random_art.RetryableErrorUpdate retryErrorBody = 15;</code>
   */
  public name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.RetryableErrorUpdate getRetryErrorBody() {
    if (updateBodyCase_ == 15) {
       return (name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.RetryableErrorUpdate) updateBody_;
    }
    return name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.RetryableErrorUpdate.getDefaultInstance();
  }
  /**
   * <code>.name.jchein.portfolio.random_art.RetryableErrorUpdate retryErrorBody = 15;</code>
   */
  public name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.RetryableErrorUpdateOrBuilder getRetryErrorBodyOrBuilder() {
    if (updateBodyCase_ == 15) {
       return (name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.RetryableErrorUpdate) updateBody_;
    }
    return name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.RetryableErrorUpdate.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
    }
    if (seq_ != 0) {
      output.writeUInt32(2, seq_);
    }
    if (updateType_ != name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.UpdateType.IN_PAINT_QUEUE.getNumber()) {
      output.writeEnum(3, updateType_);
    }
    if (updateBodyCase_ == 13) {
      output.writeMessage(13, (name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.PercentDoneUpdate) updateBody_);
    }
    if (updateBodyCase_ == 14) {
      output.writeMessage(14, (name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.InformationUpdate) updateBody_);
    }
    if (updateBodyCase_ == 15) {
      output.writeMessage(15, (name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.RetryableErrorUpdate) updateBody_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
    }
    if (seq_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(2, seq_);
    }
    if (updateType_ != name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.UpdateType.IN_PAINT_QUEUE.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(3, updateType_);
    }
    if (updateBodyCase_ == 13) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(13, (name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.PercentDoneUpdate) updateBody_);
    }
    if (updateBodyCase_ == 14) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(14, (name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.InformationUpdate) updateBody_);
    }
    if (updateBodyCase_ == 15) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(15, (name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.RetryableErrorUpdate) updateBody_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.UpdatePaintArtworkTask)) {
      return super.equals(obj);
    }
    name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.UpdatePaintArtworkTask other = (name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.UpdatePaintArtworkTask) obj;

    boolean result = true;
    result = result && getId()
        .equals(other.getId());
    result = result && (getSeq()
        == other.getSeq());
    result = result && updateType_ == other.updateType_;
    result = result && getUpdateBodyCase().equals(
        other.getUpdateBodyCase());
    if (!result) return false;
    switch (updateBodyCase_) {
      case 13:
        result = result && getPercentDoneBody()
            .equals(other.getPercentDoneBody());
        break;
      case 14:
        result = result && getInformationBody()
            .equals(other.getInformationBody());
        break;
      case 15:
        result = result && getRetryErrorBody()
            .equals(other.getRetryErrorBody());
        break;
      case 0:
      default:
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId().hashCode();
    hash = (37 * hash) + SEQ_FIELD_NUMBER;
    hash = (53 * hash) + getSeq();
    hash = (37 * hash) + UPDATETYPE_FIELD_NUMBER;
    hash = (53 * hash) + updateType_;
    switch (updateBodyCase_) {
      case 13:
        hash = (37 * hash) + PERCENTDONEBODY_FIELD_NUMBER;
        hash = (53 * hash) + getPercentDoneBody().hashCode();
        break;
      case 14:
        hash = (37 * hash) + INFORMATIONBODY_FIELD_NUMBER;
        hash = (53 * hash) + getInformationBody().hashCode();
        break;
      case 15:
        hash = (37 * hash) + RETRYERRORBODY_FIELD_NUMBER;
        hash = (53 * hash) + getRetryErrorBody().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.UpdatePaintArtworkTask parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.UpdatePaintArtworkTask parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.UpdatePaintArtworkTask parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.UpdatePaintArtworkTask parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.UpdatePaintArtworkTask parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.UpdatePaintArtworkTask parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.UpdatePaintArtworkTask parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.UpdatePaintArtworkTask parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.UpdatePaintArtworkTask parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.UpdatePaintArtworkTask parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.UpdatePaintArtworkTask parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.UpdatePaintArtworkTask parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.UpdatePaintArtworkTask prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code name.jchein.portfolio.random_art.UpdatePaintArtworkTask}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:name.jchein.portfolio.random_art.UpdatePaintArtworkTask)
      name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.UpdatePaintArtworkTaskOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.ExampleProto.internal_static_name_jchein_portfolio_random_art_UpdatePaintArtworkTask_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.ExampleProto.internal_static_name_jchein_portfolio_random_art_UpdatePaintArtworkTask_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.UpdatePaintArtworkTask.class, name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.UpdatePaintArtworkTask.Builder.class);
    }

    // Construct using name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.UpdatePaintArtworkTask.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      id_ = "";

      seq_ = 0;

      updateType_ = 0;

      updateBodyCase_ = 0;
      updateBody_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.ExampleProto.internal_static_name_jchein_portfolio_random_art_UpdatePaintArtworkTask_descriptor;
    }

    @java.lang.Override
    public name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.UpdatePaintArtworkTask getDefaultInstanceForType() {
      return name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.UpdatePaintArtworkTask.getDefaultInstance();
    }

    @java.lang.Override
    public name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.UpdatePaintArtworkTask build() {
      name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.UpdatePaintArtworkTask result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.UpdatePaintArtworkTask buildPartial() {
      name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.UpdatePaintArtworkTask result = new name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.UpdatePaintArtworkTask(this);
      result.id_ = id_;
      result.seq_ = seq_;
      result.updateType_ = updateType_;
      if (updateBodyCase_ == 13) {
        if (percentDoneBodyBuilder_ == null) {
          result.updateBody_ = updateBody_;
        } else {
          result.updateBody_ = percentDoneBodyBuilder_.build();
        }
      }
      if (updateBodyCase_ == 14) {
        if (informationBodyBuilder_ == null) {
          result.updateBody_ = updateBody_;
        } else {
          result.updateBody_ = informationBodyBuilder_.build();
        }
      }
      if (updateBodyCase_ == 15) {
        if (retryErrorBodyBuilder_ == null) {
          result.updateBody_ = updateBody_;
        } else {
          result.updateBody_ = retryErrorBodyBuilder_.build();
        }
      }
      result.updateBodyCase_ = updateBodyCase_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.UpdatePaintArtworkTask) {
        return mergeFrom((name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.UpdatePaintArtworkTask)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.UpdatePaintArtworkTask other) {
      if (other == name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.UpdatePaintArtworkTask.getDefaultInstance()) return this;
      if (!other.getId().isEmpty()) {
        id_ = other.id_;
        onChanged();
      }
      if (other.getSeq() != 0) {
        setSeq(other.getSeq());
      }
      if (other.updateType_ != 0) {
        setUpdateTypeValue(other.getUpdateTypeValue());
      }
      switch (other.getUpdateBodyCase()) {
        case PERCENTDONEBODY: {
          mergePercentDoneBody(other.getPercentDoneBody());
          break;
        }
        case INFORMATIONBODY: {
          mergeInformationBody(other.getInformationBody());
          break;
        }
        case RETRYERRORBODY: {
          mergeRetryErrorBody(other.getRetryErrorBody());
          break;
        }
        case UPDATEBODY_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.UpdatePaintArtworkTask parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.UpdatePaintArtworkTask) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int updateBodyCase_ = 0;
    private java.lang.Object updateBody_;
    public UpdateBodyCase
        getUpdateBodyCase() {
      return UpdateBodyCase.forNumber(
          updateBodyCase_);
    }

    public Builder clearUpdateBody() {
      updateBodyCase_ = 0;
      updateBody_ = null;
      onChanged();
      return this;
    }


    private java.lang.Object id_ = "";
    /**
     * <code>string id = 1;</code>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string id = 1;</code>
     */
    public Builder setId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1;</code>
     */
    public Builder clearId() {
      
      id_ = getDefaultInstance().getId();
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1;</code>
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      id_ = value;
      onChanged();
      return this;
    }

    private int seq_ ;
    /**
     * <code>uint32 seq = 2;</code>
     */
    public int getSeq() {
      return seq_;
    }
    /**
     * <code>uint32 seq = 2;</code>
     */
    public Builder setSeq(int value) {
      
      seq_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 seq = 2;</code>
     */
    public Builder clearSeq() {
      
      seq_ = 0;
      onChanged();
      return this;
    }

    private int updateType_ = 0;
    /**
     * <code>.name.jchein.portfolio.random_art.UpdateType updateType = 3;</code>
     */
    public int getUpdateTypeValue() {
      return updateType_;
    }
    /**
     * <code>.name.jchein.portfolio.random_art.UpdateType updateType = 3;</code>
     */
    public Builder setUpdateTypeValue(int value) {
      updateType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.name.jchein.portfolio.random_art.UpdateType updateType = 3;</code>
     */
    public name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.UpdateType getUpdateType() {
      @SuppressWarnings("deprecation")
      name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.UpdateType result = name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.UpdateType.valueOf(updateType_);
      return result == null ? name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.UpdateType.UNRECOGNIZED : result;
    }
    /**
     * <code>.name.jchein.portfolio.random_art.UpdateType updateType = 3;</code>
     */
    public Builder setUpdateType(name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.UpdateType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      updateType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.name.jchein.portfolio.random_art.UpdateType updateType = 3;</code>
     */
    public Builder clearUpdateType() {
      
      updateType_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.PercentDoneUpdate, name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.PercentDoneUpdate.Builder, name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.PercentDoneUpdateOrBuilder> percentDoneBodyBuilder_;
    /**
     * <code>.name.jchein.portfolio.random_art.PercentDoneUpdate percentDoneBody = 13;</code>
     */
    public boolean hasPercentDoneBody() {
      return updateBodyCase_ == 13;
    }
    /**
     * <code>.name.jchein.portfolio.random_art.PercentDoneUpdate percentDoneBody = 13;</code>
     */
    public name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.PercentDoneUpdate getPercentDoneBody() {
      if (percentDoneBodyBuilder_ == null) {
        if (updateBodyCase_ == 13) {
          return (name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.PercentDoneUpdate) updateBody_;
        }
        return name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.PercentDoneUpdate.getDefaultInstance();
      } else {
        if (updateBodyCase_ == 13) {
          return percentDoneBodyBuilder_.getMessage();
        }
        return name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.PercentDoneUpdate.getDefaultInstance();
      }
    }
    /**
     * <code>.name.jchein.portfolio.random_art.PercentDoneUpdate percentDoneBody = 13;</code>
     */
    public Builder setPercentDoneBody(name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.PercentDoneUpdate value) {
      if (percentDoneBodyBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        updateBody_ = value;
        onChanged();
      } else {
        percentDoneBodyBuilder_.setMessage(value);
      }
      updateBodyCase_ = 13;
      return this;
    }
    /**
     * <code>.name.jchein.portfolio.random_art.PercentDoneUpdate percentDoneBody = 13;</code>
     */
    public Builder setPercentDoneBody(
        name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.PercentDoneUpdate.Builder builderForValue) {
      if (percentDoneBodyBuilder_ == null) {
        updateBody_ = builderForValue.build();
        onChanged();
      } else {
        percentDoneBodyBuilder_.setMessage(builderForValue.build());
      }
      updateBodyCase_ = 13;
      return this;
    }
    /**
     * <code>.name.jchein.portfolio.random_art.PercentDoneUpdate percentDoneBody = 13;</code>
     */
    public Builder mergePercentDoneBody(name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.PercentDoneUpdate value) {
      if (percentDoneBodyBuilder_ == null) {
        if (updateBodyCase_ == 13 &&
            updateBody_ != name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.PercentDoneUpdate.getDefaultInstance()) {
          updateBody_ = name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.PercentDoneUpdate.newBuilder((name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.PercentDoneUpdate) updateBody_)
              .mergeFrom(value).buildPartial();
        } else {
          updateBody_ = value;
        }
        onChanged();
      } else {
        if (updateBodyCase_ == 13) {
          percentDoneBodyBuilder_.mergeFrom(value);
        }
        percentDoneBodyBuilder_.setMessage(value);
      }
      updateBodyCase_ = 13;
      return this;
    }
    /**
     * <code>.name.jchein.portfolio.random_art.PercentDoneUpdate percentDoneBody = 13;</code>
     */
    public Builder clearPercentDoneBody() {
      if (percentDoneBodyBuilder_ == null) {
        if (updateBodyCase_ == 13) {
          updateBodyCase_ = 0;
          updateBody_ = null;
          onChanged();
        }
      } else {
        if (updateBodyCase_ == 13) {
          updateBodyCase_ = 0;
          updateBody_ = null;
        }
        percentDoneBodyBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.name.jchein.portfolio.random_art.PercentDoneUpdate percentDoneBody = 13;</code>
     */
    public name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.PercentDoneUpdate.Builder getPercentDoneBodyBuilder() {
      return getPercentDoneBodyFieldBuilder().getBuilder();
    }
    /**
     * <code>.name.jchein.portfolio.random_art.PercentDoneUpdate percentDoneBody = 13;</code>
     */
    public name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.PercentDoneUpdateOrBuilder getPercentDoneBodyOrBuilder() {
      if ((updateBodyCase_ == 13) && (percentDoneBodyBuilder_ != null)) {
        return percentDoneBodyBuilder_.getMessageOrBuilder();
      } else {
        if (updateBodyCase_ == 13) {
          return (name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.PercentDoneUpdate) updateBody_;
        }
        return name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.PercentDoneUpdate.getDefaultInstance();
      }
    }
    /**
     * <code>.name.jchein.portfolio.random_art.PercentDoneUpdate percentDoneBody = 13;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.PercentDoneUpdate, name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.PercentDoneUpdate.Builder, name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.PercentDoneUpdateOrBuilder> 
        getPercentDoneBodyFieldBuilder() {
      if (percentDoneBodyBuilder_ == null) {
        if (!(updateBodyCase_ == 13)) {
          updateBody_ = name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.PercentDoneUpdate.getDefaultInstance();
        }
        percentDoneBodyBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.PercentDoneUpdate, name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.PercentDoneUpdate.Builder, name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.PercentDoneUpdateOrBuilder>(
                (name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.PercentDoneUpdate) updateBody_,
                getParentForChildren(),
                isClean());
        updateBody_ = null;
      }
      updateBodyCase_ = 13;
      onChanged();;
      return percentDoneBodyBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.InformationUpdate, name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.InformationUpdate.Builder, name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.InformationUpdateOrBuilder> informationBodyBuilder_;
    /**
     * <code>.name.jchein.portfolio.random_art.InformationUpdate informationBody = 14;</code>
     */
    public boolean hasInformationBody() {
      return updateBodyCase_ == 14;
    }
    /**
     * <code>.name.jchein.portfolio.random_art.InformationUpdate informationBody = 14;</code>
     */
    public name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.InformationUpdate getInformationBody() {
      if (informationBodyBuilder_ == null) {
        if (updateBodyCase_ == 14) {
          return (name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.InformationUpdate) updateBody_;
        }
        return name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.InformationUpdate.getDefaultInstance();
      } else {
        if (updateBodyCase_ == 14) {
          return informationBodyBuilder_.getMessage();
        }
        return name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.InformationUpdate.getDefaultInstance();
      }
    }
    /**
     * <code>.name.jchein.portfolio.random_art.InformationUpdate informationBody = 14;</code>
     */
    public Builder setInformationBody(name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.InformationUpdate value) {
      if (informationBodyBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        updateBody_ = value;
        onChanged();
      } else {
        informationBodyBuilder_.setMessage(value);
      }
      updateBodyCase_ = 14;
      return this;
    }
    /**
     * <code>.name.jchein.portfolio.random_art.InformationUpdate informationBody = 14;</code>
     */
    public Builder setInformationBody(
        name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.InformationUpdate.Builder builderForValue) {
      if (informationBodyBuilder_ == null) {
        updateBody_ = builderForValue.build();
        onChanged();
      } else {
        informationBodyBuilder_.setMessage(builderForValue.build());
      }
      updateBodyCase_ = 14;
      return this;
    }
    /**
     * <code>.name.jchein.portfolio.random_art.InformationUpdate informationBody = 14;</code>
     */
    public Builder mergeInformationBody(name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.InformationUpdate value) {
      if (informationBodyBuilder_ == null) {
        if (updateBodyCase_ == 14 &&
            updateBody_ != name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.InformationUpdate.getDefaultInstance()) {
          updateBody_ = name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.InformationUpdate.newBuilder((name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.InformationUpdate) updateBody_)
              .mergeFrom(value).buildPartial();
        } else {
          updateBody_ = value;
        }
        onChanged();
      } else {
        if (updateBodyCase_ == 14) {
          informationBodyBuilder_.mergeFrom(value);
        }
        informationBodyBuilder_.setMessage(value);
      }
      updateBodyCase_ = 14;
      return this;
    }
    /**
     * <code>.name.jchein.portfolio.random_art.InformationUpdate informationBody = 14;</code>
     */
    public Builder clearInformationBody() {
      if (informationBodyBuilder_ == null) {
        if (updateBodyCase_ == 14) {
          updateBodyCase_ = 0;
          updateBody_ = null;
          onChanged();
        }
      } else {
        if (updateBodyCase_ == 14) {
          updateBodyCase_ = 0;
          updateBody_ = null;
        }
        informationBodyBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.name.jchein.portfolio.random_art.InformationUpdate informationBody = 14;</code>
     */
    public name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.InformationUpdate.Builder getInformationBodyBuilder() {
      return getInformationBodyFieldBuilder().getBuilder();
    }
    /**
     * <code>.name.jchein.portfolio.random_art.InformationUpdate informationBody = 14;</code>
     */
    public name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.InformationUpdateOrBuilder getInformationBodyOrBuilder() {
      if ((updateBodyCase_ == 14) && (informationBodyBuilder_ != null)) {
        return informationBodyBuilder_.getMessageOrBuilder();
      } else {
        if (updateBodyCase_ == 14) {
          return (name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.InformationUpdate) updateBody_;
        }
        return name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.InformationUpdate.getDefaultInstance();
      }
    }
    /**
     * <code>.name.jchein.portfolio.random_art.InformationUpdate informationBody = 14;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.InformationUpdate, name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.InformationUpdate.Builder, name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.InformationUpdateOrBuilder> 
        getInformationBodyFieldBuilder() {
      if (informationBodyBuilder_ == null) {
        if (!(updateBodyCase_ == 14)) {
          updateBody_ = name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.InformationUpdate.getDefaultInstance();
        }
        informationBodyBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.InformationUpdate, name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.InformationUpdate.Builder, name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.InformationUpdateOrBuilder>(
                (name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.InformationUpdate) updateBody_,
                getParentForChildren(),
                isClean());
        updateBody_ = null;
      }
      updateBodyCase_ = 14;
      onChanged();;
      return informationBodyBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.RetryableErrorUpdate, name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.RetryableErrorUpdate.Builder, name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.RetryableErrorUpdateOrBuilder> retryErrorBodyBuilder_;
    /**
     * <code>.name.jchein.portfolio.random_art.RetryableErrorUpdate retryErrorBody = 15;</code>
     */
    public boolean hasRetryErrorBody() {
      return updateBodyCase_ == 15;
    }
    /**
     * <code>.name.jchein.portfolio.random_art.RetryableErrorUpdate retryErrorBody = 15;</code>
     */
    public name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.RetryableErrorUpdate getRetryErrorBody() {
      if (retryErrorBodyBuilder_ == null) {
        if (updateBodyCase_ == 15) {
          return (name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.RetryableErrorUpdate) updateBody_;
        }
        return name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.RetryableErrorUpdate.getDefaultInstance();
      } else {
        if (updateBodyCase_ == 15) {
          return retryErrorBodyBuilder_.getMessage();
        }
        return name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.RetryableErrorUpdate.getDefaultInstance();
      }
    }
    /**
     * <code>.name.jchein.portfolio.random_art.RetryableErrorUpdate retryErrorBody = 15;</code>
     */
    public Builder setRetryErrorBody(name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.RetryableErrorUpdate value) {
      if (retryErrorBodyBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        updateBody_ = value;
        onChanged();
      } else {
        retryErrorBodyBuilder_.setMessage(value);
      }
      updateBodyCase_ = 15;
      return this;
    }
    /**
     * <code>.name.jchein.portfolio.random_art.RetryableErrorUpdate retryErrorBody = 15;</code>
     */
    public Builder setRetryErrorBody(
        name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.RetryableErrorUpdate.Builder builderForValue) {
      if (retryErrorBodyBuilder_ == null) {
        updateBody_ = builderForValue.build();
        onChanged();
      } else {
        retryErrorBodyBuilder_.setMessage(builderForValue.build());
      }
      updateBodyCase_ = 15;
      return this;
    }
    /**
     * <code>.name.jchein.portfolio.random_art.RetryableErrorUpdate retryErrorBody = 15;</code>
     */
    public Builder mergeRetryErrorBody(name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.RetryableErrorUpdate value) {
      if (retryErrorBodyBuilder_ == null) {
        if (updateBodyCase_ == 15 &&
            updateBody_ != name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.RetryableErrorUpdate.getDefaultInstance()) {
          updateBody_ = name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.RetryableErrorUpdate.newBuilder((name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.RetryableErrorUpdate) updateBody_)
              .mergeFrom(value).buildPartial();
        } else {
          updateBody_ = value;
        }
        onChanged();
      } else {
        if (updateBodyCase_ == 15) {
          retryErrorBodyBuilder_.mergeFrom(value);
        }
        retryErrorBodyBuilder_.setMessage(value);
      }
      updateBodyCase_ = 15;
      return this;
    }
    /**
     * <code>.name.jchein.portfolio.random_art.RetryableErrorUpdate retryErrorBody = 15;</code>
     */
    public Builder clearRetryErrorBody() {
      if (retryErrorBodyBuilder_ == null) {
        if (updateBodyCase_ == 15) {
          updateBodyCase_ = 0;
          updateBody_ = null;
          onChanged();
        }
      } else {
        if (updateBodyCase_ == 15) {
          updateBodyCase_ = 0;
          updateBody_ = null;
        }
        retryErrorBodyBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.name.jchein.portfolio.random_art.RetryableErrorUpdate retryErrorBody = 15;</code>
     */
    public name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.RetryableErrorUpdate.Builder getRetryErrorBodyBuilder() {
      return getRetryErrorBodyFieldBuilder().getBuilder();
    }
    /**
     * <code>.name.jchein.portfolio.random_art.RetryableErrorUpdate retryErrorBody = 15;</code>
     */
    public name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.RetryableErrorUpdateOrBuilder getRetryErrorBodyOrBuilder() {
      if ((updateBodyCase_ == 15) && (retryErrorBodyBuilder_ != null)) {
        return retryErrorBodyBuilder_.getMessageOrBuilder();
      } else {
        if (updateBodyCase_ == 15) {
          return (name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.RetryableErrorUpdate) updateBody_;
        }
        return name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.RetryableErrorUpdate.getDefaultInstance();
      }
    }
    /**
     * <code>.name.jchein.portfolio.random_art.RetryableErrorUpdate retryErrorBody = 15;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.RetryableErrorUpdate, name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.RetryableErrorUpdate.Builder, name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.RetryableErrorUpdateOrBuilder> 
        getRetryErrorBodyFieldBuilder() {
      if (retryErrorBodyBuilder_ == null) {
        if (!(updateBodyCase_ == 15)) {
          updateBody_ = name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.RetryableErrorUpdate.getDefaultInstance();
        }
        retryErrorBodyBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.RetryableErrorUpdate, name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.RetryableErrorUpdate.Builder, name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.RetryableErrorUpdateOrBuilder>(
                (name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.RetryableErrorUpdate) updateBody_,
                getParentForChildren(),
                isClean());
        updateBody_ = null;
      }
      updateBodyCase_ = 15;
      onChanged();;
      return retryErrorBodyBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:name.jchein.portfolio.random_art.UpdatePaintArtworkTask)
  }

  // @@protoc_insertion_point(class_scope:name.jchein.portfolio.random_art.UpdatePaintArtworkTask)
  private static final name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.UpdatePaintArtworkTask DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.UpdatePaintArtworkTask();
  }

  public static name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.UpdatePaintArtworkTask getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<UpdatePaintArtworkTask>
      PARSER = new com.google.protobuf.AbstractParser<UpdatePaintArtworkTask>() {
    @java.lang.Override
    public UpdatePaintArtworkTask parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new UpdatePaintArtworkTask(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<UpdatePaintArtworkTask> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<UpdatePaintArtworkTask> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.UpdatePaintArtworkTask getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

