// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto.proto

package name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto;

public interface UpdatePaintArtworkTaskOrBuilder extends
    // @@protoc_insertion_point(interface_extends:name.jchein.portfolio.random_art.UpdatePaintArtworkTask)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>uint32 seq = 2;</code>
   */
  int getSeq();

  /**
   * <code>.name.jchein.portfolio.random_art.UpdateType updateType = 3;</code>
   */
  int getUpdateTypeValue();
  /**
   * <code>.name.jchein.portfolio.random_art.UpdateType updateType = 3;</code>
   */
  name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.UpdateType getUpdateType();

  /**
   * <code>.name.jchein.portfolio.random_art.PercentDoneUpdate percentDoneBody = 13;</code>
   */
  boolean hasPercentDoneBody();
  /**
   * <code>.name.jchein.portfolio.random_art.PercentDoneUpdate percentDoneBody = 13;</code>
   */
  name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.PercentDoneUpdate getPercentDoneBody();
  /**
   * <code>.name.jchein.portfolio.random_art.PercentDoneUpdate percentDoneBody = 13;</code>
   */
  name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.PercentDoneUpdateOrBuilder getPercentDoneBodyOrBuilder();

  /**
   * <code>.name.jchein.portfolio.random_art.InformationUpdate informationBody = 14;</code>
   */
  boolean hasInformationBody();
  /**
   * <code>.name.jchein.portfolio.random_art.InformationUpdate informationBody = 14;</code>
   */
  name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.InformationUpdate getInformationBody();
  /**
   * <code>.name.jchein.portfolio.random_art.InformationUpdate informationBody = 14;</code>
   */
  name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.InformationUpdateOrBuilder getInformationBodyOrBuilder();

  /**
   * <code>.name.jchein.portfolio.random_art.RetryableErrorUpdate retryErrorBody = 15;</code>
   */
  boolean hasRetryErrorBody();
  /**
   * <code>.name.jchein.portfolio.random_art.RetryableErrorUpdate retryErrorBody = 15;</code>
   */
  name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.RetryableErrorUpdate getRetryErrorBody();
  /**
   * <code>.name.jchein.portfolio.random_art.RetryableErrorUpdate retryErrorBody = 15;</code>
   */
  name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.RetryableErrorUpdateOrBuilder getRetryErrorBodyOrBuilder();

  public name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto.UpdatePaintArtworkTask.UpdateBodyCase getUpdateBodyCase();
}
