// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto.proto

package name.jchein.portfolio.services.randomArt.paintGateway.grpc.proto;

public interface CreatePaintArtworkTaskOrBuilder extends
    // @@protoc_insertion_point(interface_extends:name.jchein.portfolio.random_art.CreatePaintArtworkTask)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string seedPrefix = 7;</code>
   */
  java.lang.String getSeedPrefix();
  /**
   * <code>string seedPrefix = 7;</code>
   */
  com.google.protobuf.ByteString
      getSeedPrefixBytes();

  /**
   * <code>string seedSuffix = 8;</code>
   */
  java.lang.String getSeedSuffix();
  /**
   * <code>string seedSuffix = 8;</code>
   */
  com.google.protobuf.ByteString
      getSeedSuffixBytes();

  /**
   * <code>bool newModel = 9;</code>
   */
  boolean getNewModel();

  /**
   * <code>string renderPolicy = 10;</code>
   */
  java.lang.String getRenderPolicy();
  /**
   * <code>string renderPolicy = 10;</code>
   */
  com.google.protobuf.ByteString
      getRenderPolicyBytes();

  /**
   * <code>string stagingPolicy = 11;</code>
   */
  java.lang.String getStagingPolicy();
  /**
   * <code>string stagingPolicy = 11;</code>
   */
  com.google.protobuf.ByteString
      getStagingPolicyBytes();
}
