// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto.proto

package name.jchein.portfolio.services.paint.gateway.grpc;

/**
 * <pre>
 * Acknowledgement will be used to determine when it is Ok to CLOSE a FINISHED task or DROP an ERROR or CANCELLED task.
 * </pre>
 *
 * Protobuf type {@code name.jchein.portfolio.services.paint.gateway.AcknowledgePaintArtworkTask}
 */
public  final class AcknowledgePaintArtworkTask extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:name.jchein.portfolio.services.paint.gateway.AcknowledgePaintArtworkTask)
    AcknowledgePaintArtworkTaskOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AcknowledgePaintArtworkTask.newBuilder() to construct.
  private AcknowledgePaintArtworkTask(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AcknowledgePaintArtworkTask() {
    id_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private AcknowledgePaintArtworkTask(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            id_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return name.jchein.portfolio.services.paint.gateway.grpc.PaintGatewayProto.internal_static_name_jchein_portfolio_services_paint_gateway_AcknowledgePaintArtworkTask_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return name.jchein.portfolio.services.paint.gateway.grpc.PaintGatewayProto.internal_static_name_jchein_portfolio_services_paint_gateway_AcknowledgePaintArtworkTask_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            name.jchein.portfolio.services.paint.gateway.grpc.AcknowledgePaintArtworkTask.class, name.jchein.portfolio.services.paint.gateway.grpc.AcknowledgePaintArtworkTask.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private volatile java.lang.Object id_;
  /**
   * <pre>
   * uint32 seq = 2;
   * </pre>
   *
   * <code>string id = 1;</code>
   */
  public java.lang.String getId() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      id_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * uint32 seq = 2;
   * </pre>
   *
   * <code>string id = 1;</code>
   */
  public com.google.protobuf.ByteString
      getIdBytes() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      id_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof name.jchein.portfolio.services.paint.gateway.grpc.AcknowledgePaintArtworkTask)) {
      return super.equals(obj);
    }
    name.jchein.portfolio.services.paint.gateway.grpc.AcknowledgePaintArtworkTask other = (name.jchein.portfolio.services.paint.gateway.grpc.AcknowledgePaintArtworkTask) obj;

    boolean result = true;
    result = result && getId()
        .equals(other.getId());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static name.jchein.portfolio.services.paint.gateway.grpc.AcknowledgePaintArtworkTask parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static name.jchein.portfolio.services.paint.gateway.grpc.AcknowledgePaintArtworkTask parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static name.jchein.portfolio.services.paint.gateway.grpc.AcknowledgePaintArtworkTask parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static name.jchein.portfolio.services.paint.gateway.grpc.AcknowledgePaintArtworkTask parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static name.jchein.portfolio.services.paint.gateway.grpc.AcknowledgePaintArtworkTask parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static name.jchein.portfolio.services.paint.gateway.grpc.AcknowledgePaintArtworkTask parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static name.jchein.portfolio.services.paint.gateway.grpc.AcknowledgePaintArtworkTask parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static name.jchein.portfolio.services.paint.gateway.grpc.AcknowledgePaintArtworkTask parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static name.jchein.portfolio.services.paint.gateway.grpc.AcknowledgePaintArtworkTask parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static name.jchein.portfolio.services.paint.gateway.grpc.AcknowledgePaintArtworkTask parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static name.jchein.portfolio.services.paint.gateway.grpc.AcknowledgePaintArtworkTask parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static name.jchein.portfolio.services.paint.gateway.grpc.AcknowledgePaintArtworkTask parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(name.jchein.portfolio.services.paint.gateway.grpc.AcknowledgePaintArtworkTask prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Acknowledgement will be used to determine when it is Ok to CLOSE a FINISHED task or DROP an ERROR or CANCELLED task.
   * </pre>
   *
   * Protobuf type {@code name.jchein.portfolio.services.paint.gateway.AcknowledgePaintArtworkTask}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:name.jchein.portfolio.services.paint.gateway.AcknowledgePaintArtworkTask)
      name.jchein.portfolio.services.paint.gateway.grpc.AcknowledgePaintArtworkTaskOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return name.jchein.portfolio.services.paint.gateway.grpc.PaintGatewayProto.internal_static_name_jchein_portfolio_services_paint_gateway_AcknowledgePaintArtworkTask_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return name.jchein.portfolio.services.paint.gateway.grpc.PaintGatewayProto.internal_static_name_jchein_portfolio_services_paint_gateway_AcknowledgePaintArtworkTask_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              name.jchein.portfolio.services.paint.gateway.grpc.AcknowledgePaintArtworkTask.class, name.jchein.portfolio.services.paint.gateway.grpc.AcknowledgePaintArtworkTask.Builder.class);
    }

    // Construct using name.jchein.portfolio.services.paint.gateway.grpc.AcknowledgePaintArtworkTask.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      id_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return name.jchein.portfolio.services.paint.gateway.grpc.PaintGatewayProto.internal_static_name_jchein_portfolio_services_paint_gateway_AcknowledgePaintArtworkTask_descriptor;
    }

    @java.lang.Override
    public name.jchein.portfolio.services.paint.gateway.grpc.AcknowledgePaintArtworkTask getDefaultInstanceForType() {
      return name.jchein.portfolio.services.paint.gateway.grpc.AcknowledgePaintArtworkTask.getDefaultInstance();
    }

    @java.lang.Override
    public name.jchein.portfolio.services.paint.gateway.grpc.AcknowledgePaintArtworkTask build() {
      name.jchein.portfolio.services.paint.gateway.grpc.AcknowledgePaintArtworkTask result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public name.jchein.portfolio.services.paint.gateway.grpc.AcknowledgePaintArtworkTask buildPartial() {
      name.jchein.portfolio.services.paint.gateway.grpc.AcknowledgePaintArtworkTask result = new name.jchein.portfolio.services.paint.gateway.grpc.AcknowledgePaintArtworkTask(this);
      result.id_ = id_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof name.jchein.portfolio.services.paint.gateway.grpc.AcknowledgePaintArtworkTask) {
        return mergeFrom((name.jchein.portfolio.services.paint.gateway.grpc.AcknowledgePaintArtworkTask)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(name.jchein.portfolio.services.paint.gateway.grpc.AcknowledgePaintArtworkTask other) {
      if (other == name.jchein.portfolio.services.paint.gateway.grpc.AcknowledgePaintArtworkTask.getDefaultInstance()) return this;
      if (!other.getId().isEmpty()) {
        id_ = other.id_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      name.jchein.portfolio.services.paint.gateway.grpc.AcknowledgePaintArtworkTask parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (name.jchein.portfolio.services.paint.gateway.grpc.AcknowledgePaintArtworkTask) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object id_ = "";
    /**
     * <pre>
     * uint32 seq = 2;
     * </pre>
     *
     * <code>string id = 1;</code>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * uint32 seq = 2;
     * </pre>
     *
     * <code>string id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * uint32 seq = 2;
     * </pre>
     *
     * <code>string id = 1;</code>
     */
    public Builder setId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * uint32 seq = 2;
     * </pre>
     *
     * <code>string id = 1;</code>
     */
    public Builder clearId() {
      
      id_ = getDefaultInstance().getId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * uint32 seq = 2;
     * </pre>
     *
     * <code>string id = 1;</code>
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      id_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:name.jchein.portfolio.services.paint.gateway.AcknowledgePaintArtworkTask)
  }

  // @@protoc_insertion_point(class_scope:name.jchein.portfolio.services.paint.gateway.AcknowledgePaintArtworkTask)
  private static final name.jchein.portfolio.services.paint.gateway.grpc.AcknowledgePaintArtworkTask DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new name.jchein.portfolio.services.paint.gateway.grpc.AcknowledgePaintArtworkTask();
  }

  public static name.jchein.portfolio.services.paint.gateway.grpc.AcknowledgePaintArtworkTask getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AcknowledgePaintArtworkTask>
      PARSER = new com.google.protobuf.AbstractParser<AcknowledgePaintArtworkTask>() {
    @java.lang.Override
    public AcknowledgePaintArtworkTask parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new AcknowledgePaintArtworkTask(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<AcknowledgePaintArtworkTask> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AcknowledgePaintArtworkTask> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public name.jchein.portfolio.services.paint.gateway.grpc.AcknowledgePaintArtworkTask getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

