// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto.proto

package name.jchein.portfolio.services.paint.gateway.grpc;

public interface AcknowledgePaintArtworkTaskOrBuilder extends
    // @@protoc_insertion_point(interface_extends:name.jchein.portfolio.services.paint.gateway.AcknowledgePaintArtworkTask)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * uint32 seq = 2;
   * </pre>
   *
   * <code>string id = 1;</code>
   */
  java.lang.String getId();
  /**
   * <pre>
   * uint32 seq = 2;
   * </pre>
   *
   * <code>string id = 1;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();
}
