// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto.proto

package name.jchein.portfolio.services.paint.gateway.grpc;

public interface ArtworkTaskProgressEventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:name.jchein.portfolio.services.paint.gateway.ArtworkTaskProgressEvent)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <pre>
   * uint32 seq = 2;
   * </pre>
   *
   * <code>.name.jchein.portfolio.services.paint.gateway.TaskStateType taskState = 3;</code>
   */
  int getTaskStateValue();
  /**
   * <pre>
   * uint32 seq = 2;
   * </pre>
   *
   * <code>.name.jchein.portfolio.services.paint.gateway.TaskStateType taskState = 3;</code>
   */
  name.jchein.portfolio.services.paint.gateway.grpc.TaskStateType getTaskState();

  /**
   * <code>uint32 percentPainted = 4;</code>
   */
  int getPercentPainted();

  /**
   * <code>string message = 5;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 5;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
