// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto.proto

package name.jchein.portfolio.services.paint.gateway.grpc;

public interface RequestReceivedOrBuilder extends
    // @@protoc_insertion_point(interface_extends:name.jchein.portfolio.services.paint.gateway.RequestReceived)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();
}
